.TH "include/Administrador.hpp" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Administrador.hpp \- Representa um administrador do sistema\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'Usuario\&.hpp'\fP
.br
\fC#include 'NivelDeAcesso\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdministrador\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Representa um administrador do sistema\&. 

Especializa \fBUsuario\fP com privilégios para gerenciamento do sistema, incluindo catálogo, estoque, compras e clientes\&.
.PP
\fBSee also\fP
.RS 4
\fBUsuario\fP 
.PP
\fBCatalogo\fP 
.PP
\fBEstoque\fP 
.PP
\fBCompra\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
