.TH "Administrador" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Administrador
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUsuario\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdministrador\fP (int \fBid\fP, const std::string &\fBnome\fP, const std::string &\fBemail\fP, const std::string &\fBsenha\fP, const std::string &nivelAcesso)"
.br
.RI "Construtor do administrador\&. "
.ti -1c
.RI "std::string \fBgetNivelAcesso\fP () const"
.br
.ti -1c
.RI "void \fBgerenciarCatalogo\fP ()"
.br
.RI "Gerencia o catálogo (CRUD de produtos) "
.ti -1c
.RI "void \fBacessarDadosClientes\fP ()"
.br
.RI "Acessa dados de clientes\&. "
.ti -1c
.RI "void \fBgerenciarCompras\fP ()"
.br
.RI "Gerencia compras realizadas\&. "
.ti -1c
.RI "void \fBgerenciarEstoque\fP ()"
.br
.RI "Gerencia estoque\&. "
.ti -1c
.RI "void \fBgerenciarPerfisClientes\fP ()"
.br
.RI "Gerencia perfis de clientes\&. "
.in -1c

Public Member Functions inherited from \fBUsuario\fP
.in +1c
.ti -1c
.RI "\fBUsuario\fP (int \fBid\fP, const std::string &\fBnome\fP, const std::string &\fBemail\fP, const std::string &\fBsenha\fP)"
.br
.RI "Construtor da classe \fBUsuario\fP\&. "
.ti -1c
.RI "virtual \fB~Usuario\fP ()=default"
.br
.RI "Destrutor virtual da classe \fBUsuario\fP\&. "
.ti -1c
.RI "int \fBgetId\fP () const"
.br
.RI "Retorna o ID do usuário\&. "
.ti -1c
.RI "std::string \fBgetNome\fP () const"
.br
.RI "Retorna o nome do usuário\&. "
.ti -1c
.RI "std::string \fBgetEmail\fP () const"
.br
.RI "Retorna o email do usuário\&. "
.ti -1c
.RI "std::string \fBgetSenha\fP () const"
.br
.RI "Retorna a senha do usuário\&. "
.ti -1c
.RI "void \fBsetNome\fP (const std::string &\fBnome\fP)"
.br
.RI "Define o nome do usuário\&. "
.ti -1c
.RI "void \fBsetEmail\fP (const std::string &\fBemail\fP)"
.br
.RI "Define o email do usuário\&. "
.ti -1c
.RI "void \fBsetSenha\fP (const std::string &\fBsenha\fP)"
.br
.RI "Define a senha do usuário\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBUsuario\fP
.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.RI "Identificador único do usuário\&. "
.ti -1c
.RI "std::string \fBnome\fP"
.br
.RI "Nome completo\&. "
.ti -1c
.RI "std::string \fBemail\fP"
.br
.RI "Email de login\&. "
.ti -1c
.RI "std::string \fBsenha\fP"
.br
.RI "Senha (hash) "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
