.TH "Administrador" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Administrador
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdministrador\fP (const std::string &nome, const std::string &email, const std::string &senha)"
.br
.RI "Construtor do administrador\&. "
.ti -1c
.RI "void \fBgerenciarCatalogo\fP ()"
.br
.RI "Gerencia o catálogo (CRUD de produtos) "
.ti -1c
.RI "void \fBgerenciarEstoque\fP ()"
.br
.RI "Gerencia estoque\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUsuario\fP \fBusuario\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
