.TH "Carrinho" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Carrinho
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBcalculaValorTotal\fP (const std::vector< std::string > &produtos)"
.br
.ti -1c
.RI "float \fBcalculaTotalDeItens\fP (const std::vector< std::string > &produtos)"
.br
.ti -1c
.RI "void \fB_checkout\fP ()"
.br
.ti -1c
.RI "std::vector< \fBProduto\fP > \fB_getProdutos\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBProduto\fP > \fBprodutos\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
