.TH "include/Carrinho.hpp" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Carrinho.hpp \- Gerencia os itens selecionados por um cliente antes da compra\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Produto\&.hpp'\fP
.br
\fC#include 'Usuario\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCarrinho\fP"
.br
.RI "Classe que representa o carrinho de compras de um usuário\&. "
.in -1c
.SH "Detailed Description"
.PP 
Gerencia os itens selecionados por um cliente antes da compra\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
