.TH "include/Catalogo.hpp" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Catalogo.hpp \- Gerencia a coleção de produtos exibida aos clientes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Produto\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCatalogo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gerencia a coleção de produtos exibida aos clientes\&. 

Responsável por armazenar e disponibilizar os produtos, permitindo filtragem, busca e ordenação\&.
.PP
\fBSee also\fP
.RS 4
\fBProduto\fP 
.PP
\fBAdministrador\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
