.TH "Catalogo" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Catalogo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCatalogo\fP ()"
.br
.RI "Construtor padrão\&. "
.ti -1c
.RI "void \fBadicionarProduto\fP (const \fBProduto\fP &produto)"
.br
.RI "Adiciona um produto ao catálogo\&. "
.ti -1c
.RI "void \fBremoverProduto\fP (int id)"
.br
.RI "Remove um produto pelo ID\&. "
.ti -1c
.RI "std::vector< \fBProduto\fP > \fBgetProdutos\fP () const"
.br
.RI "Retorna todos os produtos\&. "
.ti -1c
.RI "std::vector< \fBProduto\fP > \fBfiltrarPorCategoria\fP (const std::string &categoria)"
.br
.RI "Filtra produtos por categoria\&. "
.ti -1c
.RI "void \fBordenarPorPreco\fP (bool crescente)"
.br
.RI "Ordena produtos por preço\&. "
.ti -1c
.RI "std::vector< \fBProduto\fP > \fBbuscarProduto\fP (const std::string &termo)"
.br
.RI "Busca produto pelo nome\&. "
.ti -1c
.RI "std::string \fBlistarNomes\fP () const"
.br
.RI "Exibe nomes dos produtos\&. "
.ti -1c
.RI "std::string \fBlistarPrecos\fP () const"
.br
.RI "Exibe preços dos produtos\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Catalogo::ordenarPorPreco (bool crescente)"

.PP
Ordena produtos por preço\&. 
.PP
\fBParameters\fP
.RS 4
\fIcrescente\fP true = crescente, false = decrescente 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
