.TH "include/Cliente.hpp" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Cliente.hpp \- Define o ator '\fBCliente\fP' no e-commerce\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Carrinho\&.hpp'\fP
.br
\fC#include 'Usuario\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCliente\fP"
.br
.RI "Representa um cliente no sistema\&. "
.in -1c
.SH "Detailed Description"
.PP 
Define o ator '\fBCliente\fP' no e-commerce\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
