.TH "Cliente" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cliente \- Representa um cliente no sistema\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Cliente\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCliente\fP (const std::string &nome, const std::string &email, const std::string &senha)"
.br
.RI "Construtor da classe \fBCliente\fP\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUsuario\fP \fBusuario\fP"
.br
.RI "Dados cadastrais e credenciais do cliente (Composição) "
.ti -1c
.RI "\fBCarrinho\fP \fBcarrinho\fP"
.br
.RI "\fBCarrinho\fP de compras vinculado a este cliente (Composição) "
.in -1c
.SH "Detailed Description"
.PP 
Representa um cliente no sistema\&. 


.IP "\(bu" 2
Utiliza composição para agregar os dados base de um \fBUsuario\fP e um \fBCarrinho\fP de compras próprio\&. 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Cliente::Cliente (const std::string & nome, const std::string & email, const std::string & senha)"

.PP
Construtor da classe \fBCliente\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fInome\fP Nome completo do cliente\&. 
.br
\fIemail\fP E-mail de login\&. 
.br
\fIsenha\fP Senha de acesso\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
