.TH "Compra" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Compra
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompra\fP (int idCompra, int idCliente, const std::vector< \fBProduto\fP > &itens, const std::string &dataCompra, const std::string &metodoPagamento)"
.br
.RI "Construtor da compra\&. "
.ti -1c
.RI "int \fBgetIdCompra\fP () const"
.br
.ti -1c
.RI "int \fBgetIdCliente\fP () const"
.br
.ti -1c
.RI "std::vector< \fBProduto\fP > \fBgetItens\fP () const"
.br
.ti -1c
.RI "std::string \fBgetDataCompra\fP () const"
.br
.ti -1c
.RI "std::string \fBgetStatus\fP () const"
.br
.ti -1c
.RI "std::string \fBgetMetodoPagamento\fP () const"
.br
.ti -1c
.RI "bool \fBprocessarPagamento\fP ()"
.br
.RI "Processa o pagamento da compra\&. "
.ti -1c
.RI "void \fBatualizarStatus\fP (const std::string &novoStatus)"
.br
.RI "Atualiza o status da compra\&. "
.ti -1c
.RI "void \fBatualizarEstoque\fP ()"
.br
.RI "Atualiza o estoque com base nos itens comprados\&. "
.ti -1c
.RI "std::string \fBgerarResumo\fP () const"
.br
.RI "Gera um resumo da compra\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool Compra::processarPagamento ()"

.PP
Processa o pagamento da compra\&. 
.PP
\fBReturns\fP
.RS 4
true se pagamento aprovado 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
