.TH "include/Compra.hpp" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Compra.hpp \- Representa uma transação finalizada no sistema\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Produto\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompra\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Representa uma transação finalizada no sistema\&. 

Responsável por armazenar os dados de uma compra, processar pagamento, atualizar status e interagir com o estoque\&.
.PP
\fBSee also\fP
.RS 4
\fBEstoque\fP 
.PP
\fBCliente\fP 
.PP
\fBAdministrador\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
