.TH "Compra" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Compra
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompra\fP (const std::string &emailCliente, const std::vector< \fBProduto\fP > &itens)"
.br
.RI "Constrói uma nova \fBCompra\fP a partir dos itens do carrinho no momento do checkout\&. "
.ti -1c
.RI "void \fBexibirCompra\fP () const"
.br
.RI "Exibe no console os dados da compra (data, itens e total)\&. "
.ti -1c
.RI "double \fBgetTotal\fP () const"
.br
.ti -1c
.RI "const std::string & \fBgetData\fP () const"
.br
.ti -1c
.RI "const std::vector< \fBProduto\fP > & \fBgetItens\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsalvarHistorico\fP (const \fBCompra\fP &compra, const std::string &txtpath='compras\&.txt')"
.br
.RI "Salva uma compra no arquivo de histórico (modo 'append')\&. "
.ti -1c
.RI "static std::vector< \fBCompra\fP > \fBcarregarHistorico\fP (const std::string &emailCliente, const std::string &txtpath='compras\&.txt')"
.br
.RI "Carrega o histórico de compras de um cliente específico\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Compra::Compra (const std::string & emailCliente, const std::vector< \fBProduto\fP > & itens)"

.PP
Constrói uma nova \fBCompra\fP a partir dos itens do carrinho no momento do checkout\&. 
.PP
\fBParameters\fP
.RS 4
\fIemailCliente\fP Email do cliente que realizou a compra\&. 
.br
\fIitens\fP Itens (produtos) que fazem parte da compra\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
