.TH "include/Compra.hpp" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Compra.hpp \- Representa o registro de uma compra finalizada por um cliente\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Produto\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompra\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Representa o registro de uma compra finalizada por um cliente\&. 

Armazena os itens, o valor total e a data de uma compra, e oferece persistência simples em arquivo de texto para consulta posterior (histórico de compras)\&.
.PP
\fBSee also\fP
.RS 4
\fBCarrinho\fP 
.PP
\fBProduto\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
