.TH "desenhos" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
desenhos
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBtriangulo_ps\fP ()"
.br
.ti -1c
.RI "static void \fBbolinha_ps\fP ()"
.br
.ti -1c
.RI "static void \fBx_ps\fP ()"
.br
.ti -1c
.RI "static void \fBquadrado_ps\fP ()"
.br
.ti -1c
.RI "static void \fBcontroles\fP ()"
.br
.ti -1c
.RI "static void \fBcontrole_super_nintendo\fP ()"
.br
.ti -1c
.RI "static void \fBcontrole_arcade\fP ()"
.br
.ti -1c
.RI "static void \fBnome_loja\fP ()"
.br
.ti -1c
.RI "static void \fBtela_1\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
