.TH "include/Estoque.hpp" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Estoque.hpp \- Gerencia a disponibilidade física e quantidades dos produtos em um arquivo \&.txt\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'Produto\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEstoque\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gerencia a disponibilidade física e quantidades dos produtos em um arquivo \&.txt\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
