.TH "include/Estoque.hpp" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Estoque.hpp \- Gerencia a disponibilidade física dos produtos\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEstoque\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gerencia a disponibilidade física dos produtos\&. 

Controla quantidades em estoque, gerencia alertas de itens e realiza reservas durante o processo de compra\&.
.PP
\fBSee also\fP
.RS 4
\fBProduto\fP 
.PP
\fBAdministrador\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
