.TH "md_design_2Notas_01do_01Professor_2notas-C7" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_design_2Notas_01do_01Professor_2notas-C7 \- notas-C7 
.PP

.IP "\(bu" 2
o makefile está com problemas: rodar um 'make' ou 'make app' não compila por dependências do gcov\&. apenas usar o gcov no target coverage\&.
.PP
.PP
os arquivos de coverage (\&.html) não deveriam ser gerados na raiz do projeto\&. isso deixa o seu projeto bagunçado\&. é análogo aos arquivos \&.o em build\&.
.IP "\(bu" 2
por algum motivo o 'make coverage' apaga e recompila tudo do zero\&. isso está incorreto\&. somente os arquivos \&.gcda podem ser apagados\&.
.IP "\(bu" 2
a cobertura final (máxima) foi de 53\&.9%\&. entrega não está de acordo com o mínimo de cobertura exigida (60%)\&. 
.PP

