.TH "md_design_2Notas_01do_01Professor_2notas-C6" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_design_2Notas_01do_01Professor_2notas-C6 \- notas-C6 
.PP

.IP "\(bu" 2
Doxygen basicamente inexistente\&.
.PP
.PP
Embora os diagramas de classe sejam legais, não foi feita nenhuma descrição da estrutura proposta ou de funcionalidades\&.
.IP "\(bu" 2
README em branco\&. 
.PP

