.TH "md_design_2Notas_01do_01Professor_2notas" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_design_2Notas_01do_01Professor_2notas \- notas 
.PP

.IP "\(bu" 2
user stories: bom trabalho, bem padrão\&. todas stories corretas e bem explicadas\&. embora a quantidade de critérios de aceitação tenham sido suficientes, mais critérios ajudariam na entrega 7\&.
.PP
.PP
crc: não tem produto\&.\&.\&.
.IP "\(bu" 2
notas gerais: ótimo trabalho\&. a próxima entrega deve fica mais fácil dada a modelagem que foi feita por vocês 
.PP

