.TH "md_README" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- PDS2-2026-PF-grupo7 
.PP
 Compilação
.PP
$ make
.PP
Atenção: Criar antes um diretório \&./build/ Execução
.PP
$ make run
.PP
Compilação Testes
.PP
$ make tests
.PP
Execução Testes
.PP
$ make run_tests
.PP
Relatório de Cobertura
.PP
Para imprimir o relatório simplificado no próprio Terminal, utilizar:
.PP
$ make coverage
.PP
Para gerar o relatório em HTML, utilizar:
.PP
$ make html_coverage 
