.TH "include/Controle/Menu.hpp" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Controle/Menu.hpp \- Controla as interfaces de menus e fluxos de navegação do sistema\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Usuario\&.hpp'\fP
.br
\fC#include 'EstadosDeMenu\&.hpp'\fP
.br
\fC#include 'Carrinho\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMenu\fP"
.br
.RI "Classe estática responsável por renderizar as telas e gerenciar as entradas do usuário\&. "
.in -1c
.SH "Detailed Description"
.PP 
Controla as interfaces de menus e fluxos de navegação do sistema\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
