.TH "Menu" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu \- Classe estática responsável por renderizar as telas e gerenciar as entradas do usuário\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Menu\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBEstadosDeMenu\fP \fBmenuInicial\fP ()"
.br
.RI "Exibe o menu para usuários não autenticados\&. "
.ti -1c
.RI "static void \fBiniciar\fP ()"
.br
.RI "Inicia o loop principal do sistema de menus\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classe estática responsável por renderizar as telas e gerenciar as entradas do usuário\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBEstadosDeMenu\fP Menu::menuInicial ()\fC [static]\fP"

.PP
Exibe o menu para usuários não autenticados\&. 
.PP
\fBReturns\fP
.RS 4
EstadosDeMenu O próximo estado selecionado (ex: Login ou Sair)\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
