.TH "Menu" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu \- \fBMenu\fP para controle dos Menus da aplicação\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Menu\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMenu_01\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMenu\fP para controle dos Menus da aplicação\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
