.TH "include/NivelDeAcesso.hpp" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/NivelDeAcesso.hpp \- Define as permissões de acesso dos usuários no sistema\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBNivelDeAcesso\fP { \fBCliente\fP = 1, \fBAdmin\fP = 2 }"
.br
.RI "Enumeração para controle de privilégios de Usuários\&. "
.in -1c
.SH "Detailed Description"
.PP 
Define as permissões de acesso dos usuários no sistema\&. 


.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBNivelDeAcesso\fP\fC [strong]\fP"

.PP
Enumeração para controle de privilégios de Usuários\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICliente \fP\fP
Acesso restrito a compras e dados pessoais\&. 
.TP
\fB\fIAdmin \fP\fP
Acesso total de gerenciamento do sistema\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
