.TH "Produto" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Produto
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProduto\fP (const std::string &nome, const std::string &plataforma, const std::string &genero, double preco)"
.br
.ti -1c
.RI "void \fBexibirProduto\fP () const"
.br
.RI "Printa os dados do jogo\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBnome\fP"
.br
.ti -1c
.RI "std::string \fBplataforma\fP"
.br
.ti -1c
.RI "std::string \fBgenero\fP"
.br
.ti -1c
.RI "double \fBpreco\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
