.TH "include/Produto.hpp" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Produto.hpp \- Representa um jogo disponível no sistema de e-commerce\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProduto\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Representa um jogo disponível no sistema de e-commerce\&. 

Armazena todas as informações de um produto do catálogo, incluindo preço, nome, plataforma e gênero\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
