.TH "Produto" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Produto
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProduto\fP (int id, const std::string &nome, const std::string &categoria, float preco, int quantidadeEstoque)"
.br
.ti -1c
.RI "int \fBgetId\fP () const"
.br
.ti -1c
.RI "std::string \fBgetNome\fP () const"
.br
.ti -1c
.RI "std::string \fBgetCategoria\fP () const"
.br
.ti -1c
.RI "float \fBgetPreco\fP () const"
.br
.ti -1c
.RI "int \fBgetQuantidadeEstoque\fP () const"
.br
.ti -1c
.RI "void \fBsetId\fP (int id)"
.br
.ti -1c
.RI "void \fBsetNome\fP (const std::string &nome)"
.br
.ti -1c
.RI "void \fBsetCategoria\fP (const std::string &categoria)"
.br
.ti -1c
.RI "void \fBsetPreco\fP (float preco)"
.br
.ti -1c
.RI "void \fBsetQuantidadeEstoque\fP (int quantidadeEstoque)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
