.TH "include/Usuario.hpp" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Usuario.hpp \- Classe base abstrata para todos os usuários do sistema\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'NivelDeAcesso\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUsuario\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classe base abstrata para todos os usuários do sistema\&. 

Centraliza atributos e comportamentos comuns a qualquer ator que interaja com o sistema, sendo especializada por \fBCliente\fP e \fBAdministrador\fP\&.
.PP
\fBSee also\fP
.RS 4
\fBCliente\fP 
.PP
\fBAdministrador\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
