.TH "Usuario" 3 "Loja de Jogos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Usuario
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUsuario\fP (const std::string &\fBnome\fP, const std::string &\fBemail\fP, const std::string &\fBsenha\fP, int \fBnivelDeAcesso\fP)"
.br
.RI "Construtor da classe \fBUsuario\fP\&. "
.ti -1c
.RI "bool \fBpossuiAcesso\fP (int acesso) const"
.br
.RI "Verifica se o usuario possui o acesso requerido\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::unique_ptr< \fBUsuario\fP > \fBlogin\fP (const std::string &\fBemail\fP, const std::string &\fBsenha\fP, const std::string &txtpath='usuarios\&.txt')"
.br
.RI "Método para realizar o login do usuário buscando os dados em um arquivo txt\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnivelDeAcesso\fP"
.br
.RI "Nível de acesso ao sistema\&. "
.ti -1c
.RI "std::string \fBnome\fP"
.br
.RI "Nome completo\&. "
.ti -1c
.RI "std::string \fBemail\fP"
.br
.RI "Email de login\&. "
.ti -1c
.RI "std::string \fBsenha\fP"
.br
.RI "Senha\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Usuario::Usuario (const std::string & nome, const std::string & email, const std::string & senha, int nivelDeAcesso)"

.PP
Construtor da classe \fBUsuario\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fInivelDeAcesso\fP Nível de acesso ao sistema cliente = 1, admin = 3 
.br
\fInome\fP Nome completo 
.br
\fIemail\fP Email de acesso 
.br
\fIsenha\fP Senha do usuário 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::unique_ptr< \fBUsuario\fP > Usuario::login (const std::string & email, const std::string & senha, const std::string & txtpath = \fC'usuarios\&.txt'\fP)\fC [static]\fP"

.PP
Método para realizar o login do usuário buscando os dados em um arquivo txt\&. 
.PP
\fBParameters\fP
.RS 4
\fIemail\fP 
.br
\fIsenha\fP 
.br
\fItxtpath\fP 
.RE
.PP
\fBReturns\fP
.RS 4
std::unique_ptr<Usuario> 
.RE
.PP

.SS "bool Usuario::possuiAcesso (int acesso) const"

.PP
Verifica se o usuario possui o acesso requerido\&. 
.PP
\fBParameters\fP
.RS 4
\fIacesso\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true 
.PP
false 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Loja de Jogos from the source code\&.
